// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV-Quw1AOJPI82M3ZtjjdN-fzdeZaxfK8',
    appId: '1:1079312687821:web:3b760ae6aeefcf62d83f84',
    messagingSenderId: '1079312687821',
    projectId: 'caltrack-adf35',
    authDomain: 'caltrack-adf35.firebaseapp.com',
    storageBucket: 'caltrack-adf35.firebasestorage.app',
    measurementId: 'G-5FXHQRF798',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjmSiEbZoWH4mevSVn83-GlqxeJNwUnIA',
    appId: '1:1079312687821:android:6b0ac26129bed396d83f84',
    messagingSenderId: '1079312687821',
    projectId: 'caltrack-adf35',
    storageBucket: 'caltrack-adf35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfOA52Vjnl61xBRhGa4rHtYoWMvozFxEo',
    appId: '1:1079312687821:ios:435196bb025a2c1ad83f84',
    messagingSenderId: '1079312687821',
    projectId: 'caltrack-adf35',
    storageBucket: 'caltrack-adf35.firebasestorage.app',
    iosBundleId: 'com.example.caltrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfOA52Vjnl61xBRhGa4rHtYoWMvozFxEo',
    appId: '1:1079312687821:ios:435196bb025a2c1ad83f84',
    messagingSenderId: '1079312687821',
    projectId: 'caltrack-adf35',
    storageBucket: 'caltrack-adf35.firebasestorage.app',
    iosBundleId: 'com.example.caltrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV-Quw1AOJPI82M3ZtjjdN-fzdeZaxfK8',
    appId: '1:1079312687821:web:48e9fb06aebc3294d83f84',
    messagingSenderId: '1079312687821',
    projectId: 'caltrack-adf35',
    authDomain: 'caltrack-adf35.firebaseapp.com',
    storageBucket: 'caltrack-adf35.firebasestorage.app',
    measurementId: 'G-2M6KJM7F1B',
  );
}
